/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyrupsRouteImport } from './routes/syrups'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NewSaleRouteImport } from './routes/new-sale'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SyrupsRoute = SyrupsRouteImport.update({
  id: '/syrups',
  path: '/syrups',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NewSaleRoute = NewSaleRouteImport.update({
  id: '/new-sale',
  path: '/new-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/inventory': typeof InventoryRoute
  '/new-sale': typeof NewSaleRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/syrups': typeof SyrupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/inventory': typeof InventoryRoute
  '/new-sale': typeof NewSaleRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/syrups': typeof SyrupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categories': typeof CategoriesRoute
  '/inventory': typeof InventoryRoute
  '/new-sale': typeof NewSaleRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/syrups': typeof SyrupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categories'
    | '/inventory'
    | '/new-sale'
    | '/products'
    | '/settings'
    | '/syrups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/categories'
    | '/inventory'
    | '/new-sale'
    | '/products'
    | '/settings'
    | '/syrups'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categories'
    | '/inventory'
    | '/new-sale'
    | '/products'
    | '/settings'
    | '/syrups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CategoriesRoute: typeof CategoriesRoute
  InventoryRoute: typeof InventoryRoute
  NewSaleRoute: typeof NewSaleRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  SyrupsRoute: typeof SyrupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syrups': {
      id: '/syrups'
      path: '/syrups'
      fullPath: '/syrups'
      preLoaderRoute: typeof SyrupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-sale': {
      id: '/new-sale'
      path: '/new-sale'
      fullPath: '/new-sale'
      preLoaderRoute: typeof NewSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CategoriesRoute: CategoriesRoute,
  InventoryRoute: InventoryRoute,
  NewSaleRoute: NewSaleRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  SyrupsRoute: SyrupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
